# Project information
site_name: A Beginner's Guide to Docker
site_author: Ananya Gupta
site_description: A Beginner's Guide to Docker

# Repository
repo_name: Ananya2003Gupta/Beginner-s-Guide-to-Docker
repo_url: https://github.com/Ananya2003Gupta/Beginner-s-Guide-to-Docker

# Copyright
copyright: Copyright &copy; 2023 Ananya Gupta

# Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - navigation.footer
    - navigation.indexes
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: sky
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: white
  font:
    text: Roboto
    code: Roboto Mono

markdown_extensions:
  - attr_list
  - md_in_html

# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'

nav:
  - Home:
    - index.md 
    - Table of Contents: Content.md
    - Introduction:
      - 1.1  What is Docker: Introduction/WhatIsDocker.md
      - 1.2  Advantages of Using Docker: Introduction/AdvantagesOfUsingDocker.md
      - 1.3  Docker Architecture: Introduction/DockerArchitecture.md
      - 1.4  Running A Blogging Platform: Introduction/RunningABloggingPlatform.md
    - Getting Started with Docker:
      - 2.1  Installing Docker: GettingStartedWithDocker/InstallingDocker.md
      - 2.2  Docker Editions and Versions: GettingStartedWithDocker/DockerEditionsAndVersions.md
      - 2.3  Running the First Docker Container: GettingStartedWithDocker/RunningTheFirstDockerContainer.md
    - Docker Images:
      - 3.1  Understanding Docker Images: DockerImages/UnderstandingDockerImages.md
      - 3.2  Docker Hub and Official Repositories: DockerImages/DockerHubAndOfficialRepositories.md
      - 3.3  Building Custom Docker Images: DockerImages/BuildingCustomDockerImages.md
      - 3.4  Working with Dockerfiles: DockerImages/WorkingWithDockerfile.md
